// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: example.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExampleGrpc_SayHello_FullMethodName = "/example_grpc.ExampleGrpc/SayHello"
)

// ExampleGrpcClient is the client API for ExampleGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExampleGrpcClient interface {
	SayHello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type exampleGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewExampleGrpcClient(cc grpc.ClientConnInterface) ExampleGrpcClient {
	return &exampleGrpcClient{cc}
}

func (c *exampleGrpcClient) SayHello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, ExampleGrpc_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExampleGrpcServer is the server API for ExampleGrpc service.
// All implementations must embed UnimplementedExampleGrpcServer
// for forward compatibility.
type ExampleGrpcServer interface {
	SayHello(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedExampleGrpcServer()
}

// UnimplementedExampleGrpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExampleGrpcServer struct{}

func (UnimplementedExampleGrpcServer) SayHello(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedExampleGrpcServer) mustEmbedUnimplementedExampleGrpcServer() {}
func (UnimplementedExampleGrpcServer) testEmbeddedByValue()                     {}

// UnsafeExampleGrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExampleGrpcServer will
// result in compilation errors.
type UnsafeExampleGrpcServer interface {
	mustEmbedUnimplementedExampleGrpcServer()
}

func RegisterExampleGrpcServer(s grpc.ServiceRegistrar, srv ExampleGrpcServer) {
	// If the following call pancis, it indicates UnimplementedExampleGrpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExampleGrpc_ServiceDesc, srv)
}

func _ExampleGrpc_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleGrpcServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExampleGrpc_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleGrpcServer).SayHello(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// ExampleGrpc_ServiceDesc is the grpc.ServiceDesc for ExampleGrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExampleGrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "example_grpc.ExampleGrpc",
	HandlerType: (*ExampleGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _ExampleGrpc_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example.proto",
}
